StepCreateCD: Clean up temporary directory and add more robust tests
hashicorp/packer-plugin-sdk pull request #62
Opened 2021-04-29 20:28 UTC by saleemrashid

This adds more robust tests that check the actual filenames and contents in the temporary directory, as well as removing the temporary directory in the step cleanup. This also tests adding folders, which wasn't previously being tested. 

The motivation for checking the content is to allow tests for #61 that test how `cd_files` and `cd_content` interact (e.g. that `cd_content` correctly takes precedence over `cd_files`).

2021-05-04 09:57 UTC, azr requested changes
Hello there, thanks for opening, this LGTM and you simply need to fix some linting issues: https://app.circleci.com/pipelines/github/hashicorp/packer-plugin-sdk/372/workflows/dd870b66-cf48-4d09-ba04-abdc676ba893/jobs/3054

Thanks for your time 🙂

2021-05-12 12:45 UTC, azr commented on multistep/commonsteps/step_create_cdrom_test.go
> +		}
```suggestion
		err := os.MkdirAll(filepath.Dir(path), 0777)
		if err != nil {
			t.Fatalf("mkdir -p: %s", err)
		}
		err = ioutil.WriteFile(path, []byte(content), 0666)
		if err != nil {
			t.Fatalf("writing file: %s", err)
		}
```

2021-05-12 12:47 UTC, azr commented on multistep/commonsteps/step_create_cdrom_test.go
> +	}
```suggestion
	err := filepath.WalkDir(rootFolder, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			t.Fatalf("walking folder: %s", err)
		}

		if !d.IsDir() {
			name, _ := filepath.Rel(rootFolder, path)

			expectedContent, ok := expected[name]
			if !ok {
				t.Fatalf("unexpected file: %s", name)
			}

			content, err := ioutil.ReadFile(path)
			if err != nil {
				t.Fatalf("reading file: %s", err)
			}
			if string(content) != expectedContent {
				t.Fatalf("unexpected content: %s", name)
			}

			delete(expected, name)
		}

		return nil
	})
	if err != nil {
		t.Fatalf("WalkDir: %v", err)
	}
	if len(expected) != 0 {
		t.Fatalf("missing files: %v", expected)
	}
```

2021-05-12 12:53 UTC, azr commented
Fixed the linting issues !

2021-05-12 12:53 UTC, merged

2021-05-12 23:52 UTC, saleemrashid commented
Thank you, and sorry I hadn't had a chance to fix them :pray:

2021-05-18 06:32 UTC, azr commented
👍🏼 🙂